mabel:
  blindness-duration: 100
  glowing-interval: 600
  glowing-duration: 100
redhat:
  duration: 100
  regeneration-amplifier: 0
  resistance-amplifier: 0
chechirecat:
  speed-duration: 60
  speed-amplifier: 0
kelti:
  invisibility-duration: 100
bill:
  cd: 3600
eunice:
  duration: 100
  cd: 1200
dodo:
  speed-duration: 60
faketurtle:
  resistence-amplifier: 1
  slowness-amplifier: 1
  invisibility-duration: 100
  jump-amplifier: 1
leaf:
  gadget-interval: 900
victoria:
  radiusX: 5
  radiusY: 5
  radiusZ: 5
chest-locations:
  1:
    x: -1017
    y: 87
    z: 1980
  2:
    x: -1020
    y: 90
    z: 1993
  3:
    x: -989
    y: 92
    z: 1976
  4:
    x: -1019
    y: 92
    z: 1989
  5:
    x: -998
    y: 93
    z: 1980
  6:
    x: -987
    y: 99
    z: 1980
  7:
    x: -992
    y: 99
    z: 1991
  8:
    x: -995
    y: 104
    z: 1991
  9:
    x: -1014
    y: 103
    z: 1996
  10:
    x: -1019
    y: 99
    z: 1982
  11:
    x: -1013
    y: 115
    z: 1988
  12:
    x: -992
    y: 123
    z: 1980
  13:
    x: -1016
    y: 128
    z: 1994
  14:
    x: -1002
    y: 133
    z: 1990
  15:
    x: -1016
    y: 107
    z: 1991
  16:
    x: -1004
    y: 108
    z: 1974
  17:
    x: -991
    y: 116
    z: 1997
  18:
    x: -991
    y: 118
    z: 1995
